// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordFrequency.Infrastructure.Data;

#nullable disable

namespace WordFrequency.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618011059_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WordFrequency.Domain.Entities.WordFrequencyResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("TotalWords")
                        .HasColumnType("int");

                    b.Property<int>("UniqueWords")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("WordFrequency.Domain.Entities.WordFrequencyResult", b =>
                {
                    b.OwnsMany("WordFrequency.Domain.Entities.WordCount", "Results", b1 =>
                        {
                            b1.Property<Guid>("WordFrequencyResultId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("Count")
                                .HasColumnType("int");

                            b1.Property<int>("Rank")
                                .HasColumnType("int");

                            b1.Property<string>("Word")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.HasKey("WordFrequencyResultId", "Id");

                            b1.ToTable("Analyses");

                            b1.ToJson("Results");

                            b1.WithOwner()
                                .HasForeignKey("WordFrequencyResultId");
                        });

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
